# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  appinventaris:
    image: appinventaris
    build:
      context: .
      dockerfile: AppInventaris/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5079:5079
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
